services:
  - type: web
    name: inequality-escape-room-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ANTHROPIC_API_KEY
        sync: false
